
package org.openclinica.ws.event.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ws", targetNamespace = "http://openclinica.org/ws/event/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    org.openclinica.ws.event.v1.ObjectFactory.class,
    org.openclinica.ws.beans.ObjectFactory.class
})
public interface Ws {


    /**
     * 
     * @param scheduleRequest
     * @return
     *     returns org.openclinica.ws.event.v1.ScheduleResponse
     */
    @WebMethod
    @WebResult(name = "scheduleResponse", targetNamespace = "http://openclinica.org/ws/event/v1", partName = "scheduleResponse")
    public ScheduleResponse schedule(
        @WebParam(name = "scheduleRequest", targetNamespace = "http://openclinica.org/ws/event/v1", partName = "scheduleRequest")
        ScheduleRequest scheduleRequest);

}
