
package org.openclinica.ws.data.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ws", targetNamespace = "http://openclinica.org/ws/data/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    org.openclinica.ws.data.v1.ObjectFactory.class,
    org.openclinica.ws.beans.ObjectFactory.class
})
public interface Ws {


    /**
     * import odm data
     * 
     * @param importRequest
     * @return
     *     returns org.openclinica.ws.data.v1.ImportResponse
     */
    @WebMethod(operationName = "import")
    @WebResult(name = "importResponse", targetNamespace = "http://openclinica.org/ws/data/v1", partName = "importResponse")
    public ImportResponse dataImport(
        @WebParam(name = "importRequest", targetNamespace = "http://openclinica.org/ws/data/v1", partName = "importRequest")
        Object importRequest);

}
