
package org.openclinica.ws.studysubject.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import org.openclinica.ws.beans.ListStudySubjectsInStudyType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ws", targetNamespace = "http://openclinica.org/ws/studySubject/v1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    org.openclinica.ws.beans.ObjectFactory.class,
    org.openclinica.ws.studysubject.v1.ObjectFactory.class
})
public interface Ws {


    /**
     * 
     * @param isStudySubjectRequest
     * @return
     *     returns org.openclinica.ws.studysubject.v1.IsStudySubjectResponse
     */
    @WebMethod
    @WebResult(name = "isStudySubjectResponse", targetNamespace = "http://openclinica.org/ws/studySubject/v1", partName = "isStudySubjectResponse")
    public IsStudySubjectResponse isStudySubject(
        @WebParam(name = "isStudySubjectRequest", targetNamespace = "http://openclinica.org/ws/studySubject/v1", partName = "isStudySubjectRequest")
        IsStudySubjectRequest isStudySubjectRequest);

    /**
     * 
     * @param listAllByStudyRequest
     * @return
     *     returns org.openclinica.ws.studysubject.v1.ListAllByStudyResponse
     */
    @WebMethod
    @WebResult(name = "listAllByStudyResponse", targetNamespace = "http://openclinica.org/ws/studySubject/v1", partName = "listAllByStudyResponse")
    public ListAllByStudyResponse listAllByStudy(
        @WebParam(name = "listAllByStudyRequest", targetNamespace = "http://openclinica.org/ws/studySubject/v1", partName = "listAllByStudyRequest")
        ListStudySubjectsInStudyType listAllByStudyRequest);

    /**
     * 
     * @param createRequest
     * @return
     *     returns org.openclinica.ws.studysubject.v1.CreateResponse
     */
    @WebMethod
    @WebResult(name = "createResponse", targetNamespace = "http://openclinica.org/ws/studySubject/v1", partName = "createResponse")
    public CreateResponse create(
        @WebParam(name = "createRequest", targetNamespace = "http://openclinica.org/ws/studySubject/v1", partName = "createRequest")
        CreateRequest createRequest);

}
